### ISSUE TITLE
What if I do download a car?

### ISSUE THREAD

**Issue by livibetter** [duraki/virtualcar#3]
Would I face the same [consequence](https://www.youtube.com/watch?v=ALZZx1xmAzg)?

**Comment by duraki** [comment]
Depends. Is it open-source?

**Comment by livibetter** [comment]
No. An extra question, what if I download an armor car, assuming I successfully download it before anything happens,  then I download another car while sitting in it, will I be safe?

**Comment by duraki** [comment]
It depends again. You better run if the armor car is made in China.

**Comment by duraki** [comment]
Ooups, sorry. I just saw you are from Taiwan.

**Comment by livibetter** [comment]
I feel you have been evading my questions, something fishy is going on here, what if you are actually with some government's black agency.
