### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by JL01152** [duraki/virtualcar#5]
Hi, I tried to install per your instructions and received the following error:

dirtynix@dirtynix:~/virtualcar$ make
gcc -pthread src/virtualcar.c   -o virtualcar
In file included from src/virtualcar.c:50:0:
src/car.c: In function ‘send_can_frame’:
src/car.c:74:32: warning: passing argument 1 of ‘parse_canframe’ from incompatible pointer type [-Wincompatible-pointer-types]
  required_mtu = parse_canframe(&sframe, &frame);
                                ^
In file included from src/car.c:43:0,
                 from src/virtualcar.c:50:
src/include/lib.h:97:5: note: expected ‘char *’ but argument is of type ‘char **’
 int parse_canframe(char *cs, struct canfd_frame *cf);
     ^
In file included from src/virtualcar.c:51:0:
src/bus.c: At top level:
src/bus.c:44:5: error: redefinition of ‘send_can_frame’
 int send_can_frame(char *sframe)
     ^
In file included from src/virtualcar.c:50:0:
src/car.c:60:5: note: previous definition of ‘send_can_frame’ was here
 int send_can_frame(char *sframe)
     ^
In file included from src/virtualcar.c:51:0:
src/bus.c: In function ‘send_can_frame’:
src/bus.c:59:30: error: expected expression before ‘=’ token
     ifr.ifr_name[IFNAMSIZ-1[ = '\0';
                              ^
src/bus.c:64:1: error: expected ‘]’ before ‘}’ token
 }
 ^
src/bus.c:64:1: error: expected ‘;’ before ‘}’ token
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

What am I doing wrong?

**Comment by duraki** [comment]
Master is broken for a few nights. I'll push some changes tonight.

**Comment by JL01152** [comment]
Ok great. Thanks, I thought I was doing something wrong since I'm new to all this.


________________________________

**Comment by duraki** [comment]
I think this [patch](https://github.com/dn5/virtualcar/releases/tag/v1.0.0-m.patch) should fix all compiling problems. 
  
Nodes may not work correctly, and you may use older [version](https://github.com/dn5/virtualcar/commit/a7065dca5b00d00a159d35c490c28b8178b192c6) known as *vircar* previously.

**Comment by JL01152** [comment]
I compiled everything and got it working a few seconds after you made the changes. I was expectantly waiting. Sorry I didn't provide feedback right away. I got caught up reading your blog post on instructions of getting it all set up with vcan. I must say.. Just wow. That's a lot to take in at once. I got to playing with cangen and candump and was rather impressed with the all the options and all that can be done. Excellent learning tool. The amount of data coming out of an actual bus must be overwhelming. I look forward to a part3 of your blog with maybe a little more insight on how to apply your tools in a real life scenario. Also I kinda wished that the vcan could have a way of sending different canbus packets without having to type vcan0 everytime. I don't know maybe with practice I'll start to do everything without fumbling lol. Thanks for providing this tool and your development herein. I forgot to mention that like yourself I also have an older BMW. I have a 95 750i that uses canbus for communication between the DMEs, EGS, and ABS(ASC) modules. I just don't know how much of that if any of it can be human readable information as to there's no was to interact with it? Buttons,etc.

________________________________

**Comment by duraki** [comment]
Glad you made it work. Yep, we should definitely be grateful to @hartkopp and Marc for their `can-utils` package.
  
Try to experiment with other tools like `cansniffer` which shows a real-time byte change. I'm planning to implement such a thing on `canhell/sharkwheels`. There is a nice code in Python from Alexandre Blin on GitHub: (@alexandreblin) which you can learn from protocol stuff and some nice rt parsing. You should be aware of frame dataset size and a lot of occurrences on actual bus but it's just makes the thing more interesting since you gotta look for something specific.

I bet you saw it but [this paper](http://e38.org/bussystem.pdf) is interesting to read.

A lot of thing depends on the bus area. I wrote some paper on these but forgot to push from work computer so hopefully late on Monday.
  
Try to get a little comfortable with various details about CAN. You can definitely learn a few things before experimenting with your vehicle.

Nice BMW you got there :+1: Isn't that E38 iirc? Try to play with infotainment system first. A couple wrong injected frames can destroy your engine cu.
  
Enjoy.

**Comment by JL01152** [comment]
Thanks once again for taking the time to respond. I’ll also duly note the credit given to the nice people that made it possible for you to create this. Good to see you give credit where it’s due. I will continue to experiment with the tools to get familiar with the language and protocol, command set, etc. Like I said, I’m a beginner in all this and I have a long ways to go. I’ve taken it upon myself to be on fast track and try to get up to speed and contribute any findings. Thank You for providing me references and starting points. I’ll definitely pursue those pointers. As for the BMW, Yea I’ve read a lot on the subject. Can never read enough on it I must say. I have a lot of files archived on my PC from my progressive research. Just because the interne is such a volatile place. Things going missing and links dying is fairly common place. I look forward to your paper on the BMW busses. I have been able to use INPA to connect to the E38 and control various aspects of it. I connect through the D-Bus which I suspect uses a K-Line protocol of some sort because I connect with a kkl adapter. Also I connect with an ADS adapter I assembled from schematics online. This acted as some kind of Schmidt trigger to communicate on the same bus with the Engine ECUs. I eventually bought a TINYADS module as it was more finely built. I’ve been pleased with it. Not sure why I’m not able to connect to the ECUs through the obd2 kkl adapter. Anyway, I’ve grown huge interest in sniffing this bus and also the ibus you suggested to see what kind of structure the data is transmitted in. And since I mentioned the archives I have of misc information. I’ve been searching for and collecting canbus PIDs for different vehicles. I was wondering if you would be willing to take a look at these and see if you can somehow implement them into your project maybe? I’m thinking a lot of the golden information will lie in vehicle specific diagnostic and programming software. If you could trick the proprietary software into thinking it was connecting to a real car and be able to sniff different commands sent from said software would be key.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
